// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgRrKdy-OOfpvMRGyQU0I4QFlmcnjqE4',
    appId: '1:549673357963:web:dde6b548e1116a743d3a8e',
    messagingSenderId: '549673357963',
    projectId: 'buyzoondash',
    authDomain: 'buyzoondash.firebaseapp.com',
    storageBucket: 'buyzoondash.firebasestorage.app',
    measurementId: 'G-6DJGDXVQH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNp1MSc99YRRE3bg5NQci5hnePbL2oMO4',
    appId: '1:549673357963:android:9675b5d5e0b94dac3d3a8e',
    messagingSenderId: '549673357963',
    projectId: 'buyzoondash',
    storageBucket: 'buyzoondash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbxFCI2p0fT-SgtqP4diTwU5HIObSqCcY',
    appId: '1:549673357963:ios:151f465281bb23313d3a8e',
    messagingSenderId: '549673357963',
    projectId: 'buyzoondash',
    storageBucket: 'buyzoondash.firebasestorage.app',
    iosBundleId: 'com.example.buyzoonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbxFCI2p0fT-SgtqP4diTwU5HIObSqCcY',
    appId: '1:549673357963:ios:151f465281bb23313d3a8e',
    messagingSenderId: '549673357963',
    projectId: 'buyzoondash',
    storageBucket: 'buyzoondash.firebasestorage.app',
    iosBundleId: 'com.example.buyzoonapp',
  );
}
